---
- name: Add PostgreSQL apt-key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository into sources list
  apt_repository:
    repo:  deb http://apt.postgresql.org/pub/repos/apt/ {{ hostvars[inventory_hostname].ansible_distribution_release }}-pgdg main
    state: present
    filename: postgresql

- name: Add TimescaleDB apt-key
  apt_key:
    url: https://packagecloud.io/timescale/timescaledb/gpgkey
    state: present

- name: Add TimescaleDB repository into sources list
  apt_repository:
    repo: deb https://packagecloud.io/timescale/timescaledb/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    filename: timescaledb

- name: Update repositories cache and install PostgreSQL 15 and timescaledb packages
  apt:
    pkg:
      - postgresql-15
      - webitel-postgresql-15
      - timescaledb-2-postgresql-15
    update_cache: yes

- name: Execute timescaledb-tune
  shell: timescaledb-tune --quiet --yes

- name: Restart PostgreSQL on Linux
  service:
    name: postgresql
    state: restarted

- name: Enable PostgreSQL at startup (systemd)
  systemd:
    name: postgresql
    enabled: yes
  when:
    - ansible_service_mgr == "systemd"

- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: restart postgresql
  when: systemd_unit is changed

- name: Create "opensips" user, set password, grant privs
  postgresql_user:
    name: opensips
    password: webitel
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Create a new database with name "webitel"
  postgresql_db:
    name: webitel
    owner: opensips
  register: create_db
  become_user: postgres

- name: Restore database "webitel" from the file
  postgresql_db:
    name: webitel
    owner: opensips
    state: restore
    target: "{{ item }}"
  with_items:
    - /usr/share/postgresql/15/webitel/webitel-db-schema.sql
    - /usr/share/postgresql/15/webitel/webitel-db-data.sql
  become_user: postgres
  when: create_db is changed

- name: Creates a cron file under /etc/cron.d
  ansible.builtin.cron:
    name: psql daily script
    minute: "4"
    hour: "4"
    user: postgres
    job: "psql webitel < /usr/share/postgresql/15/webitel/database_helper.sql"
    cron_file: ansible_psql-database_helper